platform :ios, '13.0'
install! 'cocoapods', :disable_input_output_paths => true

use_frameworks! :linkage => :static

# This Podfile assumes a standard Flutter iOS project layout.
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), `which flutter`.strip.concat('/../..'))

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __dir__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in Generated.xcconfig"
end

flutter_tools_podhelper = File.expand_path('packages/flutter_tools/bin/podhelper', flutter_root)
require flutter_tools_podhelper

target 'Runner' do
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
    end
  end
end
